apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: kubia
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: kubia
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 30
