apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ghost
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ghost
  template:
    metadata:
      labels:
        app: ghost
    spec:
      containers:
      - image: ghost
        name: ghost
        env:
        volumeMounts:
        - mountPath: /var/lib/ghost/config.production.json
          subPath: config.production.json
          name: config
      volumes:
      - name: config
        configMap:
          defaultMode: 420
          name: ghost-config
